### PR TITLE
upgrade to aws-sdk-go-v2 - 2021-12-03

### PR DESCRIPTION
**Pull request by smcavallo**
Signed-off-by: smcavallo <smcavallo@hotmail.com>

### Description of your changes

See - https://github.com/aws/aws-sdk-go-v2/issues/1513
The endpoint issues are fixed in the latest sdk - https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-12-02
Upgrading crossplane to the latest aws-sdk-go-v2 - 2021-12-03 to fix localstack issues

Fixes #
https://github.com/crossplane/provider-aws/issues/1017

I have:

- [X ] Read and followed Crossplane's [contribution process].
- [X ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by muvaf** [comment]
@smcavallo Thanks! Have you confirmed that updating to these versions fix the issue?

**Comment by haarchri** [comment]
I can test have everything running for this Issue ;)

**Comment by haarchri** [comment]
tested with 
LocalStack CLI 0.13.1.1
Kube Version: v1.21.1

[OK] create

```
kubectl apply -f bucket.yaml 
bucket.s3.aws.crossplane.io/crossplane-test-bucket created

kubectl get managed
NAME                                                 READY   SYNCED   AGE
bucket.s3.aws.crossplane.io/crossplane-test-bucket   True    False    4m40s

aws --endpoint-url=http://127.0.0.1:4566 s3 ls
2021-12-18 07:28:40 crossplane-test-bucket
```



[FAILED] observe
`observe failed: failed to query Bucket: api error Forbidden: Forbidden`



[OK] delete

```
kubectl delete -f bucket.yaml
bucket.s3.aws.crossplane.io "crossplane-test-bucket" deleted
aws --endpoint-url=http://127.0.0.1:4566 s3 ls
```

**Comment by haarchri** [comment]
@smcavallo  did you tested again ?

**Comment by zonybob** [comment]
If this fixes Endpoint overrides of IAM via ProviderConfig spec, then I am very interested as I'm currently blocked by that. Do you need help testing or anything?

**Comment by haarchri** [comment]
@smcavallo thanks for your efford we included the SDK upgrade and tested again in #1329

**Pull request closed without merging**
