### PR TITLE
Implement nodegroup updates

### LINKED ISSUE #1073: change in  releaseVersion for nodegroup doesnt trigger reconcile
### What happened?
nodegroup resource is not being updated after i change the  releaseVersion field. 
expected behavior: change in field should trigger a nodegroup update

### How can we reproduce it?
create an eks cluster version 1.20 and a node group. 
update the eks ckuster version via crossplane (works)
update the  releaseVersion and nothing happens 

### What environment did it happen in?
Crossplane version: 

 crossplane version 1.6.1
 aws provider crossplane/provider-aws:v0.23.0
 helm provider crossplane/provider-helm:v0.9.0

### LINKED ISSUE #1455: Changes to EKS NodeGroup LaunchTemplateVersion does not update NodeGroup
### What happened?

I created a `LaunchTemplate` and a `LaunchTemplateVersion` and then created a `NodeGroup` and configured it to use the `LaunchTemplateVersion`. When I create a new `LaunchTemplateVersion` and apply the version to the `NodeGroup` I would expect that the `NodeGroup` would update to use the configured version but it does not. The `NodeGroup` status is synced and ready but when I check the AWS console it is still using the previous Version.

### How can we reproduce it?

Create `LaunchTemplate`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  annotations:
    crossplane.io/external-name: default-us-east-1a
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0cca3d8b6715c9f74
      instanceType: m5.xlarge
```

Create `LaunchTemplateVersion`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplateVersion
metadata:
  name: default-us-east-1a-ami-0cca3d8b6715c9f74
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0cca3d8b6715c9f74
      instanceType: m5.xlarge
    launchTemplateName: default-us-east-1a
    launchTemplateNameRef:
      name: default-us-east-1a
    region: us-east-1
```

Create `NodeGroup` using `LaunchTemplateVersion`
```yaml
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    amiType: CUSTOM
    capacityType: ON_DEMAND
    clusterName: cluster
    launchTemplate:
      name: default-us-east-1a
      nameRef:
        name: default-us-east-1a
      version: "2"
      versionRef:
        name: default-us-east-1a-ami-0cca3d8b6715c9f74
    nodeRole: arn:aws:iam::000000000000:role/role
    region: us-east-1
    releaseVersion: ami-06ce408c7d97c5f2d
    scalingConfig:
      maxSize: 15
      minSize: 1
```

Create new `LaunchTemplateVersion`
```yaml
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: LaunchTemplateVersion
metadata:
  name: default-us-east-1a-ami-0f80e6144aa24f34d
spec:
  deletionPolicy: Delete
  forProvider:
    launchTemplateData:
      imageID: ami-0f80e6144aa24f34d
      instanceType: m5.xlarge
    launchTemplateName: default-us-east-1a
    launchTemplateNameRef:
      name: default-us-east-1a
    region: us-east-1
```

Update `NodeGroup` with new `LaunchTemplateVersion`
```yaml
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: default-us-east-1a
spec:
  deletionPolicy: Delete
  forProvider:
    amiType: CUSTOM
    capacityType: ON_DEMAND
    clusterName: cluster
    launchTemplate:
      name: default-us-east-1a
      nameRef:
        name: default-us-east-1a
      version: "3"
      versionRef:
        name: default-us-east-1a-ami-0f80e6144aa24f34d
    nodeRole: arn:aws:iam::000000000000:role/role
    region: us-east-1
    releaseVersion: ami-06ce408c7d97c5f2d
    scalingConfig:
      maxSize: 15
      minSize: 1
```

### What environment did it happen in?
Crossplane version:  v1.9.0
Kubernetes version: v1.22.10-eks-84b4fe6

### LINKED ISSUE #1474: Implement NodegroupUpdateConfig
### What problem are you facing?
Currently, I cannot use the full NodegroupUpdate experience. Although #1469 implements updating `LaunchTemplate` and `ReleaseVersion`, I cannot recover from `PodEvictionFailures` and I cannot specify how many Nodes are allowed to be unavailable during updates.

### How could Crossplane help solve your problem?
By implementing the [NodegroupUpdateConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_NodegroupUpdateConfig.html) Property of a NodeGroup users can configure the number of unavailable nodes.

To mitigate `PodEvictionFailure`, one needs to pass the `force` flag to the update request. I think we can consider this a NodegroupUpdateConfig property as well, despite the fact that it is not according to AWS.

### PR DESCRIPTION
**Pull request by baldorch**
### Description of your changes
This PR implements almost full `NodeGroupUpdateVersion` behaviour. It allows for updating the `releaseVersion` and the `launchTemplate .version` properties of a NodeGroup. It also late initialises the `launchTemplate.version` property after creation, so that reconciliation can be performed without ambiguities.

Fixes #1073 by triggering an Update on `releaseVersion` change
Fixes #1455 by triggering an Update on `launchTemplate.version` change
Fixes #1474 by implementing NodegroupUpdateConfig and forcing if configured

I have:

- [X] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

`make reviewable test` is running as I write this. I will tick the box as soon as it finished without errors.

#### Testing LaunchTemplate and ReleaseVersion Updates
I created a NodeGroup for an existing EKS Cluster (1.22) where I configured
- `launchTemplate.ID`
- `version` 1.22
- `releaseVersion` 1.22.9-20220802
I made sure that the `launchTemplate.version` was added by the controller.

I created a new LaunchTemplate version and changed the NodeGroup to use
- `releaseVersion` 1.22.12-20220811
- `launchTemplate.version` 2
The update was constructed and performed as expected.

I edited the NodeGroup to again use `launchTemplate.version` 1 and verified that the update was performed as expected.

I updated the EKS Cluster to version 1.23 and edited the NodeGroup to use:
- `version` 1.23
- `releaseVersion` 1.23.7-20220802
- `launchTemplate.version` 2
I verified that the update was performed as expected.

I then just changed the `releaseVersion` to 1.23.9-20220811 and again verified that the update was performed as expected.

#### Testing NodeGroupUpdateConfig

I created a NodeGroup without configuring an `updateConfig` and made sure that:
- the `NodeGroupUpdateConfig` got late initialised with the default value `false` for `updateConfig.force` and `1` for `updateConfig.maxUnavailable`
- The `NodeGroupUpdateConfigStatus` was populated correctly

Then I created a Deployment and an aggressive PDB (i.e. `minAvailable: "100%"`), created a new LaunchTemplateVersion, updated the NodeGroup to use the new Version and waited for the update to fail - which it did with `PodEvictionFailure`.

I then changed the LaunchTemplateVersion back and set `updateConfig.force` to `true` and verified that the update was successful.

I also made sure that I can change the value of `updateConfig.maxUnavailable` to `2` and that this change is reconciled to AWS and also visible in the status of the NodeGroup.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by baldorch** [comment]
I would love to add a `spec.forProvider.forceUpdates` property - or something similiar - to the API to implement the last missing `UpdateNodegroupVersion` feature. Should I do this here or should I open an issue first?

**Comment by haarchri** [comment]
yes please implement 
`applyImmediately ` ??

**Comment by baldorch** [comment]
The AWS API calls it [`force`](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupVersion.html#AmazonEKS-UpdateNodegroupVersion-request-force), why not stick to their terminology?

**Comment by haarchri** [comment]
yes then use force - not checked the API

**Comment by baldorch** [comment]
@adamjohnson01 I am sorry that my PR made you feel that way and it was in no way meant to devalue your work. Thank you for teaching me about the etiquette. I appreciate that, since I am quite new to this process.

**Comment by adamjohnson01** [comment]
@baldorch, no problem. Thank you for your acknowledgement and reply!

**Comment by baldorch** [comment]
After thinking about the `force` option and other unimplemented update configuration, I would like to move the implementation to a separate issue and pull request. This keeps things here lean and simple.

There is a [NodegroupUpdateConfig AWS EKS API Object](https://docs.aws.amazon.com/eks/latest/APIReference/API_NodegroupUpdateConfig.html) where we can specify `maxUnavailable` or `maxUnavailablePercentage`. Although `force` is no property of this Object, I think the "Force" Option should live there thematically.

**Comment by baldorch** [comment]
> The last thing we want to do is keep a NodeGroup permanently updating. I think.

After thinking a bit more about this, I came to the conclusion that keeping the node Updating is exactly what we want. That is the purpose of a reconciler: Trying again and again to move Spec to Status.

We still have no information about why or if an update failed, that is why I've created #1475.

**Comment by baldorch** [comment]
Since this was not merged an I based my work on this branch I've added the changes for #1474 and the implementation of `force` to this Branch/PR.

**Review by haarchri — APPROVED** [review]
thanks we tested this function the last day in our infrastructure is working as expected - thanks for implementation ;)

**Pull request merged**
