### PR TITLE
upgrade aws-sdk-go from 1.37.4 to 1.42.0

### PR DESCRIPTION
**Pull request by smcavallo**
Signed-off-by: smcavallo <smcavallo@hotmail.com>

### Description of your changes
aws sdk released new method of configuring FIPS endpoints
See - https://github.com/aws/aws-sdk-go/pull/3938
It would be helpful to be able to use the new endpoint configuration methods in `provider-aws`

Will need to use the same version in the upstream generator:
https://github.com/aws-controllers-k8s/community/issues/1059

This was updated in the following commit ->  https://github.com/aws-controllers-k8s/code-generator/commit/edec6dad2fbd530d615d01e96f5251a806e1f36d

Open PRs:
https://github.com/aws-controllers-k8s/runtime/pull/60
https://github.com/aws-controllers-k8s/code-generator/pull/238

Fixes #
https://github.com/crossplane/provider-aws/issues/853

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
@smcavallo we need the same SDK v1 Version for provider-aws and Code-Gen please have a Look at https://github.com/crossplane/provider-aws/pull/801

**Comment by smcavallo** [comment]
> 
> 
> @smcavallo we need the same SDK v1 Version for provider-aws and Code-Gen please have a Look at #801 - If we want a newer SDK v1 Version we need First request in code-gen repo and then bump & generate all stuff in provider-aws

@haarchri - thanks - there should be links in the body of this PR for those pull requests to keep the version in sync.

**Comment by haarchri** [comment]
@smcavallo can you Change to latest code-generator commit ? SDK is updated https://github.com/aws-controllers-k8s/code-generator/blob/main/go.mod#L7

**Comment by smcavallo** [comment]
@haarchri  - resolved merge conflicts and updated the code generator commit in the Makefile to https://github.com/crossplane/provider-aws/pull/918

**Comment by haarchri** [comment]
@smcavallo can you Check https://github.com/crossplane/provider-aws/pull/1122 think i rerun generator also checked all new resources and added them to ignore list - can we Go with #1122 ?

**Comment by smcavallo** [comment]
closing in favor of https://github.com/crossplane/provider-aws/pull/1122

**Pull request closed without merging**
