### PR TITLE
feat(iam): inline policies as part of iam role

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
Signed-off-by: Ivan K <ivankatliarchuk@gmail.com>

### Description of your changes

Follow up https://github.com/crossplane-contrib/provider-aws/pull/938
Fixes #

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
In this PR only an example is part of the commit ? Can you check the controller code ? ;)

**Comment by ivankatliarchuk** [comment]
I will change the code too. Just testing it.

**Comment by ivankatliarchuk** [comment]
I'l change the code too. Just trying to understand how to build and test it on live cluster

**Comment by ivankatliarchuk** [comment]
Will close this PR in favour https://github.com/crossplane-contrib/provider-aws/pull/938, as it looks like the PR owner is still working on it

**Pull request closed without merging**
