### PR TITLE
fix version string bug

### PR DESCRIPTION
**Pull request by condaatje**
EKS has deprecated 1.16, making this change necessary for the cluster to provision.

although 1.25 is the latest release, EKS only supports 1.20-1.23

### CODE REVIEW

**Comment by haarchri** [comment]
thanks - can you check DCO signing ? then we can merge it

**Comment by condaatje** [comment]
fixed, if force-push from gitlab codespace works to get the rewritten history properly DCO'd...

**Comment by haarchri** [comment]
Think the latest possible Version in EKS is 1.24 https://aws.amazon.com/de/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/

**Comment by condaatje** [comment]
saw the upstream update to 1.21 - your call, feel free to close this if preferred.

**Pull request closed without merging**
