### PR TITLE
chore: Update owners

### PR DESCRIPTION
**Pull request by MisterMX**
### Description of your changes

Update owners with new maintainers.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

n.a.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by jbw976 — APPROVED** [review]
Thanks for updating the OWNERS file @MisterMX! 🙇‍♂️

**Comment by jbw976** [comment]
https://github.com/anagarlau and https://github.com/christopherj have been invited to maintain this repo, thank you for the continued investments! 🤩

**Comment by christophrj** [comment]
it's https://github.com/christophrj though :)

**Comment by jbw976** [comment]
The incorrect account was removed from permissions, PR to update the OWNERS.md file was opened with https://github.com/crossplane-contrib/provider-aws/pull/2139, and @christophrj has now been invited 😇

**Pull request merged**
