### PR TITLE
mark cluster as ready during creating

### LINKED ISSUE #1674: Kafka controller is waiting for MSK creation to mark ready
Kafka controller can not determine how long it will take MSK to create. As a result, it should mark ready whenever cluster creation is successful. The crossplane credential can be used to determine when the MSK cluster is actually available.

As a result of the indeterminate install time, helm marks the chart as failed. Kubevela actually uninstalls and reinstalls it, which leads to all sorts of undesirable behavior.

### PR DESCRIPTION
**Pull request by drewwells**
Fixes #1674

### CODE REVIEW

**Comment by haarchri** [comment]
if we set the status to Available we running directly update requests if needed - so we avoid this in our resources and set Available only if the API set Available

**Comment by drewwells** [comment]
I didn't understand your comment. 

MSK clusters take 30mins to provision and helm install times out in 5mins. Waiting for a completely provisioned MSK cluster is unnecessary. elasticsearch in this provider does a similar lazy provisioning to keep k8s timeouts within reason.

**Comment by haarchri** [comment]
In opensearch we using the status from the API https://github.com/crossplane-contrib/provider-aws/blob/master/pkg/controller/opensearchservice/domain/setup.go#L110

**Comment by haarchri** [comment]
`helm upgrade --wait --timeout=30m`  via HelmCli you can set the timeout - is this an option for you ?

**Comment by haarchri** [comment]
we using the status from the APi

**Pull request closed without merging**
