### PR TITLE
fix(acm): correct description for dvo

### PR DESCRIPTION
**Pull request by rushrs**
### Description of your changes
Just fixing a spelling mistake that was bothering me whilst I was looking through the provider docs.

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by MisterMX** [comment]
Thanks for the fixes, @rushrs. Could you please squash your changes into a single commit and append `:` to the conventional commit message, so it reads `fix(acm):`?

**Comment by rushrs** [comment]
just updated it @MisterMX

**Comment by rushrs** [comment]
Hi @MisterMX, I didn't realise this wasn't successful. i've made the changes to fix the error shown in CI now.

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @rushrs!

**Pull request merged**
