### PR TITLE
refactor(iam): Fix incorrect spelling

### PR DESCRIPTION
**Pull request by ivankatliarchuk**
### Description of your changes

Fixes spelling only for IAM

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Not required, as not made any changes to behavior.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by MisterMX** [comment]
@ivankatliarchuk some CI checks are failing. Can you take a look at them?

**Comment by ivankatliarchuk** [comment]
Tested in [my personal repo](https://github.com/ivankatliarchuk/crossplane-provider-aws/actions/runs/5648161567/job/15299782918?pr=2). No issues found in CI
Screenshot 2023-07-24 at 19 02 16

**Comment by MisterMX** [comment]
@ivankatliarchuk LGTM. Can you squash your changes into a single commit? Then I can merge it.

**Review by MisterMX — APPROVED** [review]
Yep. Thanks a lot @ivankatliarchuk!

**Pull request merged**
