### PR TITLE
feat: late init engineVersion if DBInstance is running within DBCluster

### PR DESCRIPTION
**Pull request by ldimitrov**
Signed-off-by: Lyuben Dimitrov <l.dimitrov@reply.de>

### Description of your changes

Late initialize the engineVersion for db Instance in case it is running within a DB cluster.

I noticed a lot of my managed `dbinstance.rds.aws.crossplane.io` resource were not Syncing. After inspection I got an error message:

```shell
update failed: cannot update DBInstance in AWS: InvalidParameterCombination: 
The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API 
```

In my setup, I have a DB Clusters with multiple DB Instances and a lot of the parameters can be only updated for the DB Cluster. I believe the engineVersion belongs also here in this check.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by haarchri — APPROVED** [review]
Thanks for add this for DBInstances belongs to Clusters

**Comment by ldimitrov** [comment]
Thanks for the approve @haarchri, I made another commit for the linting issue.

**Comment by haarchri** [comment]
Can you Check DCO Signing ?

**Comment by ldimitrov** [comment]
I messed that up by fixing the DCO. I did a rebase and now there are other commits here 🙈 Shall I better create a new pull-request and have clean commits and history?

**Comment by haarchri** [comment]
think we need to cleanup the PR after merging locally - better approach is rebase - can you take care ?

**Comment by ldimitrov** [comment]
@haarchri, sure thing! It is rebased now and looks good.

**Review by haarchri — APPROVED** [review]
LGTM

**Pull request merged**
