### PR TITLE
Feat/structured policies

### LINKED ISSUE #315: Support structured fields for IAM policies
### What problem are you facing?

Today the `IAMPolicy` type supports a `Document` string field for the IAM policy. This expects a [json document](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html#access_policies-json) for the policy definition. My use case is I would like to create IAM policy within a composition and have fields within the document patched based on other resources within the composition.

### How could Crossplane help solve your problem?

https://github.com/crossplane/provider-aws/pull/289 for s3 bucket policy offers well defined policy fields which are serialized into the json document. `IAMPolicy` should offer something similiar. The json string field `Document`  would still be preferred if non-empty, but otherwise a structured `PolicyStatement` field could be used.

Example with document:
```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: somepolicy  
spec:
  forProvider:
    name: external-name
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
  providerRef:
    name: example
  reclaimPolicy: Delete
```

Example with statement:

```yaml
apiVersion: identity.aws.crossplane.io/v1alpha1
kind: IAMPolicy
metadata:
  name: somepolicy  
spec:
  forProvider:
    name: external-name
    statement:
    - effect: "Allow"
      action: elastic-inference:Connect
      resource: "*"
  providerRef:
    name: example
  reclaimPolicy: Delete
```

### PR DESCRIPTION
**Pull request by schroeder-paul**
# Description of your changes
This allows defining policies directly as part of the YAML manifest:
```
spec:
  forProvider:
    assumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
              - eks.amazonaws.com
              - eks-fargate-pods.amazonaws.com
              - lambda.amazonaws.com
              - s3.amazonaws.com
              - rds.amazonaws.com
              - dax.amazonaws.com
          Action:
            - sts:AssumeRole
```
as well as:
```
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com",
                        "eks.amazonaws.com",
                        "eks-fargate-pods.amazonaws.com",
                        "lambda.amazonaws.com",
                        "s3.amazonaws.com",
                        "rds.amazonaws.com",
                        "dax.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
```
for Role, Policy, Secret and Queue.

Fixes #315 and is an extension of #1562 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by MisterMX — APPROVED** [review]
LGTM. Thanks a lot @schroeder-paul.

@haarchri can you take a second look and confirm that these changes are OK?

**Comment by haarchri** [comment]
@schroeder-paul can you add how you test the changes ? Overall looks good to me

**Comment by schroeder-paul** [comment]
# policy.iam Test
```bash
$ ka examples/iam/policy.yaml
policy.iam.aws.crossplane.io/somepolicy created
policy.iam.aws.crossplane.io/somepolicywithpath created
policy.iam.aws.crossplane.io/glue-policy created
```
```bash
$ kgf examples/iam/policy.yaml
NAME                 ARN                                                                               READY   SYNCED   AGE
somepolicy           arn:aws:iam::012345678910:policy/external-name                                    True    True     13s
somepolicywithpath   arn:aws:iam::012345678910:policy/some-org-unit/somepolicywithpath-external-name   True    True     13s
glue-policy          arn:aws:iam::012345678910:policy/glue-policy                                      True    True     13s
```
```yaml
# $ kg policies.iam.aws.crossplane.io somepolicy -oyaml   # the one with the new interface
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  annotations:
    crossplane.io/external-create-pending: "2023-07-10T13:32:49+02:00"
    crossplane.io/external-create-succeeded: "2023-07-10T13:32:49+02:00"
    crossplane.io/external-name: arn:aws:iam::012345678910:policy/external-name
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"iam.aws.crossplane.io/v1beta1","kind":"Policy","metadata":{"annotations":{},"name":"somepolicy"},"spec":{"forProvider":{"document":{"Statement":[{"Action":"elastic-inference:Connect","Effect":"Allow","Resource":"*","Sid":"VisualEditor0"}],"Version":"2012-10-17"},"name":"external-name"},"providerConfigRef":{"name":"example"}}}
  creationTimestamp: "2023-07-10T11:32:47Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 2
  name: somepolicy
  resourceVersion: "416228"
  uid: bfe3b40e-b660-4ee3-a58b-54ac3f72e970
spec:
  deletionPolicy: Delete
  forProvider:
    document:
      Statement:
      - Action: elastic-inference:Connect
        Effect: Allow
        Resource: '*'
        Sid: VisualEditor0
      Version: "2012-10-17"
    name: external-name
    tags:
    - key: crossplane-providerconfig
      value: example
    - key: crossplane-kind
      value: policy.iam.aws.crossplane.io
    - key: crossplane-name
      value: somepolicy
  providerConfigRef:
    name: example
status:
  atProvider:
    arn: arn:aws:iam::012345678910:policy/external-name
    defaultVersionId: v1
    isAttachable: true
    policyId: ...
  conditions:
  - lastTransitionTime: "2023-07-10T11:32:50Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-10T11:32:49Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
```yaml
# $ kg policies.iam.aws.crossplane.io somepolicywithpath -oyaml   # a policy with the old interface
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  annotations:
    crossplane.io/external-create-pending: "2023-07-10T13:32:49+02:00"
    crossplane.io/external-create-succeeded: "2023-07-10T13:32:49+02:00"
    crossplane.io/external-name: arn:aws:iam::012345678910:policy/some-org-unit/somepolicywithpath-external-name
    kubectl.kubernetes.io/last-applied-configuration: ...
  creationTimestamp: "2023-07-10T11:32:47Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 2
  name: somepolicywithpath
  resourceVersion: "416227"
  uid: fe58be0e-1486-48e1-bd37-1d53d219a6ff
spec:
  deletionPolicy: Delete
  forProvider:
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
    name: somepolicywithpath-external-name
    path: /some-org-unit/
    tags:
    - key: crossplane-kind
      value: policy.iam.aws.crossplane.io
    - key: crossplane-name
      value: somepolicywithpath
    - key: crossplane-providerconfig
      value: example
  providerConfigRef:
    name: example
status:
  atProvider:
    arn: arn:aws:iam::012345678910:policy/some-org-unit/somepolicywithpath-external-name
    defaultVersionId: v1
    isAttachable: true
    policyId: ...
  conditions:
  - lastTransitionTime: "2023-07-10T11:32:50Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-10T11:32:49Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
```bash
$ krmf examples/iam/policy.yaml
policy.iam.aws.crossplane.io "somepolicy" deleted
policy.iam.aws.crossplane.io "somepolicywithpath" deleted
policy.iam.aws.crossplane.io "glue-policy" deleted
$
```

**Comment by schroeder-paul** [comment]
# role.iam Test
```bash
$ ka examples/iam/role.yaml
role.iam.aws.crossplane.io/somerole created
role.iam.aws.crossplane.io/somenoderole created
role.iam.aws.crossplane.io/glue-role created
role.iam.aws.crossplane.io/cognito-role created
role.iam.aws.crossplane.io/rds-role created
$ kgf examples/iam/role.yaml
NAME           ARN                                           READY   SYNCED   AGE
somerole       arn:aws:iam::512236375848:role/somerole       True    True     25s
somenoderole   arn:aws:iam::512236375848:role/somenoderole   True    True     25s
glue-role      arn:aws:iam::512236375848:role/glue-role      True    True     25s
cognito-role   arn:aws:iam::512236375848:role/cognito-role   True    True     25s
rds-role       arn:aws:iam::512236375848:role/rds-role       True    True     25s
```
```yaml
# $ kg role.iam somerole -oyaml  # role with new interface
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  annotations:
    crossplane.io/external-create-pending: "2023-07-11T14:34:01+02:00"
    crossplane.io/external-create-succeeded: "2023-07-11T14:34:01+02:00"
    crossplane.io/external-name: somerole
    ...
  creationTimestamp: "2023-07-11T12:34:00Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: somerole
  ...
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicyDocument:
      Statement:
      - Action:
        - sts:AssumeRole
        Effect: Allow
        Principal:
          Service:
          - ec2.amazonaws.com
          - eks.amazonaws.com
          - eks-fargate-pods.amazonaws.com
          - lambda.amazonaws.com
          - s3.amazonaws.com
          - rds.amazonaws.com
          - dax.amazonaws.com
      Version: "2012-10-17"
    maxSessionDuration: 3600
    path: /
    tags:
    - key: k1
      value: v1
    - key: crossplane-kind
      value: role.iam.aws.crossplane.io
    - key: crossplane-name
      value: somerole
    - key: crossplane-providerconfig
      value: example
  providerConfigRef:
    name: example
status:
  atProvider:
    arn: arn:aws:iam::...:role/somerole
    roleID: ...
  conditions:
  - lastTransitionTime: "2023-07-11T12:34:02Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-11T12:34:01Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
```yaml
# $ kg role.iam somenoderole -oyaml # old interface
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  annotations:
    crossplane.io/external-create-pending: "2023-07-11T14:34:01+02:00"
    crossplane.io/external-create-succeeded: "2023-07-11T14:34:01+02:00"
    crossplane.io/external-name: somenoderole
    ...
  generation: 3
  name: somenoderole
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    maxSessionDuration: 3600
    path: /
    tags:
    - key: k2
      value: v2
    - key: crossplane-providerconfig
      value: example
    - key: crossplane-kind
      value: role.iam.aws.crossplane.io
    - key: crossplane-name
      value: somenoderole
  providerConfigRef:
    name: example
status:
  atProvider:
    arn: arn:aws:iam::...:role/somenoderole
    roleID: ...
  conditions:
  - lastTransitionTime: "2023-07-11T12:34:02Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-11T12:34:01Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```
```bash
$ krmf examples/iam/role.yaml
role.iam.aws.crossplane.io "somerole" deleted
role.iam.aws.crossplane.io "somenoderole" deleted
role.iam.aws.crossplane.io "glue-role" deleted
role.iam.aws.crossplane.io "cognito-role" deleted
role.iam.aws.crossplane.io "rds-role" deleted
```

**Comment by schroeder-paul** [comment]
# secret.secretmanager Test
```bash
$ ka examples/secretsmanager/secret.yaml
secret/example-secret-manager created
secret.secretsmanager.aws.crossplane.io/example-secret created
secret.secretsmanager.aws.crossplane.io/example-secret-policy-document created
```
```bash
$ kgf examples/secretsmanager/secret.yaml
NAME                            TYPE     DATA   AGE
secret/example-secret-manager   Opaque   1      17s

NAME                                                                     READY   SYNCED   EXTERNAL-NAME                    AGE
secret.secretsmanager.aws.crossplane.io/example-secret                   True    True     example-secret                   18s
secret.secretsmanager.aws.crossplane.io/example-secret-policy-document   True    True     example-secret-policy-document   18s
```
```yaml
# $ kg secrets.secretsmanager.aws.crossplane.io -oyaml
apiVersion: v1
items:
- apiVersion: secretsmanager.aws.crossplane.io/v1beta1
  kind: Secret
  metadata:
    annotations:
      crossplane.io/external-create-pending: "2023-07-11T14:52:28+02:00"
      crossplane.io/external-create-succeeded: "2023-07-11T14:52:29+02:00"
      crossplane.io/external-name: example-secret
      ...
    name: example-secret
    ...
  spec:
    deletionPolicy: Delete
    forProvider:
      description: test
      forceDeleteWithoutRecovery: true
      region: eu-central-1
      resourcePolicy:
        Statement:
        - Action: secretsmanager:GetSecretValue
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::...:role/somerole
          Resource: '*'
        Version: "2012-10-17"
      stringSecretRef:
        key: password
        name: example-secret-manager
        namespace: crossplane-system
        type: Opaque
      tags:
      - key: crossplane-kind
        value: secret.secretsmanager.aws.crossplane.io
      - key: crossplane-name
        value: example-secret
      - key: crossplane-providerconfig
        value: example
      - key: secret
        value: secret
    providerConfigRef:
      name: example
  status:
    atProvider:
      arn: arn:aws:secretsmanager:eu-central-1:...:secret:example-secret-UtRMwS
    conditions:
    - lastTransitionTime: "2023-07-11T12:52:30Z"
      reason: Available
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-07-11T12:52:29Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
- apiVersion: secretsmanager.aws.crossplane.io/v1beta1
  kind: Secret
  metadata:
    annotations:
      crossplane.io/external-create-pending: "2023-07-11T14:52:28+02:00"
      crossplane.io/external-create-succeeded: "2023-07-11T14:52:29+02:00"
      crossplane.io/external-name: example-secret-policy-document
      ...
    name: example-secret-policy-document
    ...
  spec:
    deletionPolicy: Delete
    forProvider:
      description: test
      forceDeleteWithoutRecovery: true
      region: eu-central-1
      resourcePolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::...:role/somerole"
              },
              "Action": "secretsmanager:GetSecretValue",
              "Resource": "*"
            }
          ]
        }
      stringSecretRef:
        key: password
        name: example-secret-manager
        namespace: crossplane-system
        type: Opaque
      tags:
      - key: crossplane-kind
        value: secret.secretsmanager.aws.crossplane.io
      - key: crossplane-name
        value: example-secret-policy-document
      - key: crossplane-providerconfig
        value: example
    providerConfigRef:
      name: example
  status:
    atProvider:
      arn: arn:aws:secretsmanager:eu-central-1:...:secret:example-secret-policy-document-wlezBM
    conditions:
    - lastTransitionTime: "2023-07-11T12:52:30Z"
      reason: Available
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-07-11T12:52:29Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
kind: List
metadata:
  resourceVersion: ""
```
```bash
$ krmf examples/secretsmanager/secret.yaml
secret "example-secret-manager" deleted
secret.secretsmanager.aws.crossplane.io "example-secret" deleted
secret.secretsmanager.aws.crossplane.io "example-secret-policy-document" deleted
```

**Comment by schroeder-paul** [comment]
# queue.sqs Test
```bash
$ ka examples/sqs/queue.yaml
queue.sqs.aws.crossplane.io/test-queue created
queue.sqs.aws.crossplane.io/test-queue2 created
```
```bash
$ kgf examples/sqs/queue.yaml
NAME          ARN                                                 READY   SYNCED   AGE
test-queue    arn:aws:sqs:eu-central-1:...:test-queue    True    True     108s
test-queue2   arn:aws:sqs:eu-central-1:...:test-queue2   True    True     108s
```
```yaml
$ kgf examples/sqs/queue.yaml -oyaml
apiVersion: v1
items:
- apiVersion: sqs.aws.crossplane.io/v1beta1
  kind: Queue
  metadata:
    annotations:
      crossplane.io/external-create-pending: "2023-07-11T15:14:43+02:00"
      crossplane.io/external-create-succeeded: "2023-07-11T15:14:43+02:00"
      crossplane.io/external-name: test-queue
      ...
    name: test-queue
    ...
  spec:
    deletionPolicy: Delete
    forProvider:
      delaySeconds: 4
      policy:
        Statement:
        - Action:
          - sqs:CreateQueue
          - sqs:SendMessage
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::...:role/somerole
          Resource: '*'
        Version: "2012-10-17"
      redrivePolicy:
        deadLetterTargetArn: arn:aws:sqs:eu-central-1:...:test-queue2
        deadLetterTargetArnRef:
          name: test-queue2
        maxReceiveCount: 1
      region: eu-central-1
    providerConfigRef:
      name: example
  status:
    atProvider:
      arn: arn:aws:sqs:eu-central-1:...:test-queue
      createdTimestamp: "2023-07-11T13:14:42Z"
      lastModifiedTimestamp: "2023-07-11T13:14:42Z"
      url: https://sqs.eu-central-1.amazonaws.com/.../test-queue
    conditions:
    - lastTransitionTime: "2023-07-11T13:14:43Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2023-07-11T13:14:43Z"
      reason: Available
      status: "True"
      type: Ready
- apiVersion: sqs.aws.crossplane.io/v1beta1
  kind: Queue
  metadata:
    annotations:
      crossplane.io/external-create-failed: "2023-07-11T15:13:48+02:00"
      crossplane.io/external-create-pending: "2023-07-11T15:14:20+02:00"
      crossplane.io/external-create-succeeded: "2023-07-11T15:14:20+02:00"
      crossplane.io/external-name: test-queue2
      ...
    name: test-queue2
    ...
  spec:
    deletionPolicy: Delete
    forProvider:
      delaySeconds: 4
      region: eu-central-1
    providerConfigRef:
      name: example
  status:
    atProvider:
      arn: arn:aws:sqs:eu-central-1:...:test-queue2
      createdTimestamp: "2023-07-11T13:14:19Z"
      lastModifiedTimestamp: "2023-07-11T13:14:19Z"
      url: https://sqs.eu-central-1.amazonaws.com/.../test-queue2
    conditions:
    - lastTransitionTime: "2023-07-11T13:14:21Z"
      reason: Available
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-07-11T13:14:20Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
kind: List
metadata:
  resourceVersion: ""
```
```bash
$ krmf examples/sqs/queue.yaml
queue.sqs.aws.crossplane.io "test-queue" deleted
queue.sqs.aws.crossplane.io "test-queue2" deleted
```

**Comment by schroeder-paul** [comment]
@haarchri added some test protocols, rebased and removed superseeded stuff.

**Pull request closed without merging**
