### PR TITLE
feat(globalaccelerator): Add support for accelerator, listener and endpointgroups

### PR DESCRIPTION
**Pull request by atarax**
### Description of your changes

Introduces support for accelerator, listener and endpointgroups. 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Code so far only has been tested on a local kind cluster. Accelerator and Listener have been manually tested for creation, deletion and updates. Endpointgroup so far has only been tested for creation and deletion.
I could add some unit-tests too. If someone might be able to give me a pointer to a simple example how this is done i would be very happy and it would shorten the time.

### Open issues

For deletion of an accelerator, all listeners need to be deleted and it has to be in disabled state. I didn't find a way to temporarily skip the delete in the case of the accelerator just being disabled, which results in some error but eventually reconciles.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by MisterMX** [comment]
Thank you very much for your contribution, @atarax. Can you rebase it on the latest master and adjust this PR to the changes made in #1827?

**Comment by atarax-test** [comment]
@MisterMX sure :)

**Comment by atarax** [comment]
@MisterMX Sure, done :)

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much for your contribution, @atarax!

**Comment by atarax** [comment]
Always a pleasure :)

**Pull request merged**
