### PR TITLE
feat(ack): bump aws sdk v1 to 1.44

### PR DESCRIPTION
**Pull request by pintonunes**
### Description of your changes

Bump AWS SDK to the latest version 1.44. After this PR we can add new resources like FunctionURLConfig and others. 
Added all new resources created with this bump to the generator-config.yaml ignore.resource_names

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
`make run` against an existing cluster and deployed a few resources 

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by haarchri** [comment]
@chlunde possible that we can brng in first https://github.com/crossplane-contrib/provider-aws/pull/1472 ?

Then we can go here with the nice work from @pintonunes

**Comment by chlunde** [comment]
@haarchri good idea and thanks for the reminder, done!

**Comment by haarchri** [comment]
@pintonunes can you rebase and Check makefile for go-sdk Version ? Thanks

**Comment by pintonunes** [comment]
Guys, any news on this PR review?

**Comment by haarchri** [comment]
i will check this week - need to check for breaking changes

**Comment by haarchri** [comment]
looks like no breaking changes on the CRD level - @pintonunes did you drive any kind of test with resources ?

**Comment by pintonunes** [comment]
I tested a couple of basic resources and everything look ok. Impossible to test everything.

**Comment by pintonunes** [comment]
@haarchri, any news? Sorry for keep pushing but I have another PR waiting to add some missing resources using the code gen and this new SDK version.

**Review by haarchri — APPROVED** [review]
thanks for driving the SDK upgrade - i tested a lot resources today - looks good on my side

**Pull request merged**
