### PR TITLE
Fix kafka initializer

### LINKED ISSUE #1611: Cluster.kafka cannot be created
### What happened?

The resource Cluster.kafka cannot be created

### How can we reproduce it?

just use the example provided, you can change some fields to more reasonable values. but it doesn't make any difference. The reconcile failed before it can start create.
(https://github.com/crossplane-contrib/provider-aws/blob/master/examples/kafka/cluster.yaml)

### What environment did it happen in?
Crossplane version:  (doesn't matter)

## Here is why it's going wrong:
The initializer of the managed resources will set the `external-name` annotation.
The `observe` function uses the `external-name` as the arn of the cluster to do the `DescribeCluster`. But a user is only allowed to describe the arn under his/her own useraccount.

Say a user is `670409000460`, and the region is `ap-southeast-1`.
Then the user can only describe the resources under `"arn:aws:kafka:ap-southeast-1:670409000460:cluster/bla/bla"`
So the `Observe` failed with 403.
I tried a way to set the `external-name` by my self to avoid it. But then I jump into annother error: 

```
  - lastTransitionTime: "2022-12-26T09:15:17Z"
    message: |-
      observe failed: failed to describe Cluster: NotFoundException: The requested resource doesn’t exist.
      {
        RespMetadata: {
          StatusCode: 404,
          RequestID: ""
        },
        InvalidParameter: "clusterArn",
        Message_: "The requested resource doesn’t exist."
      }
    reason: ReconcileError
    status: "False"
    type: Synced
```
So the here's the conclusion: the reconciler can only work correctly when `external-name` is not set, or set to correct value. While the initializer set it to the wrong value by default.

```go
func defaultMRManaged(m manager.Manager) mrManaged {
	return mrManaged{
		CriticalAnnotationUpdater: NewRetryingCriticalAnnotationUpdater(m.GetClient()),
		Finalizer:                 resource.NewAPIFinalizer(m.GetClient(), FinalizerName),
		Initializer:               NewNameAsExternalName(m.GetClient()),
		ReferenceResolver:         NewAPISimpleReferenceResolver(m.GetClient()),
		ConnectionPublisher: PublisherChain([]ConnectionPublisher{
			NewAPISecretPublisher(m.GetClient(), m.GetScheme()),
			&DisabledSecretStoreManager{},
		}),
	}
}

//...

// Initialize the given managed resource.
func (a *NameAsExternalName) Initialize(ctx context.Context, mg resource.Managed) error {
	if meta.GetExternalName(mg) != "" {
		return nil
	}
	meta.SetExternalName(mg, mg.GetName())
	return errors.Wrap(a.client.Update(ctx, mg), errUpdateManaged)
}

```

## Solution

We should add `WithInitializers` options to override the unintended default intializers

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>

fix #1611

### Description of your changes

Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by haarchri — APPROVED** [review]
LGTM - we will backport this release to 0.35 and cut a new fix release 0.35.1 shortly

**Comment by abrarcci** [comment]
Do you know when the v0.35.0 or v0.35.1 docker images will be pushed so that we can upgrade to this aws-provider verion please? As currently only v0.33 has been pushed - [docker pull crossplane/provider-aws:v0.32.0](https://registry.hub.docker.com/r/crossplane/provider-aws/tags) which was 3 months ago. When I try to update my providerconfig to point to v0.35.0 it says unable to pull image unknown manifest v0.35.0. Thanks

**Comment by hasheddan** [comment]
@abrarcci the new image location is xpkg.upbound.io/crossplane-contrib/provider-aws

**Comment by abrarcci** [comment]
Hi @hasheddan Thanks, however how do I point the provider to point to that repo? This is full error from the provider:

```
% kubectl describe provider.pkg
Name:         provider-aws
Namespace:
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: aws-config
              meta.helm.sh/release-namespace: crossplane-system
API Version:  pkg.crossplane.io/v1
Kind:         Provider
Metadata:
  Creation Timestamp:  2022-12-31T17:51:03Z
  Generation:          2
  Managed Fields:
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
      f:spec:
        .:
        f:controllerConfigRef:
          .:
          f:name:
        f:ignoreCrossplaneConstraints:
        f:package:
        f:packagePullPolicy:
        f:revisionActivationPolicy:
        f:revisionHistoryLimit:
        f:skipDependencyResolution:
    Manager:      terraform-provider-helm_v2.7.1_x5
    Operation:    Update
    Time:         2022-12-31T17:51:03Z
    API Version:  pkg.crossplane.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:currentIdentifier:
        f:currentRevision:
    Manager:         crossplane
    Operation:       Update
    Subresource:     status
    Time:            2022-12-31T18:40:18Z
  Resource Version:  11360839
  UID:               6902a5ac-6861-42cb-8c8e-ca4fe8ebb4c4
Spec:
  Controller Config Ref:
    Name:                         aws-config
  Ignore Crossplane Constraints:  false
  Package:                        crossplane/provider-aws:v0.32.0
  Package Pull Policy:            IfNotPresent
  Revision Activation Policy:     Automatic
  Revision History Limit:         1
  Skip Dependency Resolution:     false
Status:
  Conditions:
    Last Transition Time:  2022-12-31T18:40:35Z
    Reason:                UnhealthyPackageRevision
    Status:                False
    Type:                  Healthy
    Last Transition Time:  2022-12-31T18:40:18Z
    Reason:                ActivePackageRevision
    Status:                True
    Type:                  Installed
  Current Identifier:      crossplane/provider-aws:v0.32.0
  Current Revision:        provider-aws-245ce7fb587d
Events:
  Type     Reason         Age                 From                                 Message
  ----     ------         ----                ----                                 -------
  Warning  UnpackPackage  30m (x51 over 76m)  packages/provider.pkg.crossplane.io  cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: HEAD https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.35.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details): GET https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.35.0: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v0.35.0

```

**Comment by abrarcci** [comment]
`cannot unpack package: failed to fetch package digest from remote: failed to fetch package descriptor with a GET request after a previous HEAD request failure: HEAD https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.35.0: unexpected status code 404 Not Found (HEAD responses have no body, use GET for details): GET https://index.docker.io/v2/crossplane/provider-aws/manifests/v0.35.0: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v0.35.0`

**Comment by hasheddan** [comment]
@abrarcci use it in `spec.package` 👍🏻

**Comment by abrarcci** [comment]
Ok will try it, thanks

**Comment by haarchri** [comment]
We will Babackport shortly and cut 0.35.1 - think tomorrow

**Comment by abrarcci** [comment]
Thank you both, I have successfully upgraded to v0.35.0. However I and still having issues creating my msk cluster with issue:
```
Events:
  Type     Reason                         Age                  From                                     Message
  ----     ------                         ----                 ----                                     -------
  Warning  CannotObserveExternalResource  9m5s (x31 over 34m)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
           status code: 403, request id:
  Warning  CannotObserveExternalResource  20s (x12 over 6m25s)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
           status code: 403, request id:
```
I am using irsa and the role has * * privileges. I have also exec'd into the aws-provider pod and installed the aws cli and done a describe on existing cluster fine so rules out permissions issue. Do you have any idea why this might be happening, fyi the configuration gets created successfully. Happy to open a new issue if required. Thanks

**Comment by haorenfsa** [comment]
> Thank you both, I have successfully upgraded to v0.35.0. However I and still having issues creating my msk cluster with issue:
> 
> ```
> Events:
>   Type     Reason                         Age                  From                                     Message
>   ----     ------                         ----                 ----                                     -------
>   Warning  CannotObserveExternalResource  9m5s (x31 over 34m)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
>            status code: 403, request id:
>   Warning  CannotObserveExternalResource  20s (x12 over 6m25s)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
>            status code: 403, request id:
> ```
> 
> I am using irsa and the role has * * privileges. I have also exec'd into the aws-provider pod and installed the aws cli and done a describe on existing cluster fine so rules out permissions issue. Do you have any idea why this might be happening, fyi the configuration gets created successfully. Happy to open a new issue if required. Thanks

There're 2 key points you can check

What's the `crossplane.io/external-name` annotation of your resource?

Was it created before your upgrade your provider-aws or after?

This patch cannot fix the resource you created before. 
And with incorrect `crossplane.io/external-name`, the `describeCluster` request always returns 403.

**Comment by haorenfsa** [comment]
@abrarcci I just checked the release commit. This patch hasn't been backported to current v0.35.0 yet. 
You could either wait for the backport, or try use the v0.36 rc for now : The `crossplanecontrib/provider-aws:v0.36.0-rc.0.5.gb25ba836` image includes this patch.

**Comment by abrarcci** [comment]
> > Thank you both, I have successfully upgraded to v0.35.0. However I and still having issues creating my msk cluster with issue:
> > ```
> > Events:
> >   Type     Reason                         Age                  From                                     Message
> >   ----     ------                         ----                 ----                                     -------
> >   Warning  CannotObserveExternalResource  9m5s (x31 over 34m)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
> >            status code: 403, request id:
> >   Warning  CannotObserveExternalResource  20s (x12 over 6m25s)  managed/cluster.kafka.aws.crossplane.io  failed to describe Cluster: AccessDeniedException:
> >            status code: 403, request id:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am using irsa and the role has * * privileges. I have also exec'd into the aws-provider pod and installed the aws cli and done a describe on existing cluster fine so rules out permissions issue. Do you have any idea why this might be happening, fyi the configuration gets created successfully. Happy to open a new issue if required. Thanks
> 
> There're 2 key points you can check:
> 
> 1. Was it created before your upgrade your provider-aws or after?
> 2. What's the `crossplane.io/external-name` annotation of your resource?
> 
> This patch cannot fix the resource you created before. And with incorrect `crossplane.io/external-name`, the `describeCluster` request always returns 403.

Hi @haorenfsa thanks for getting back to me, the external-name annotation is the same as my claim name - it does not exist yet as it has not even been created due to the 403 error above. Thanks, let me upgrade with that tag and then destroy and try to re-create the cluster.

**Comment by abrarcci** [comment]
Hi @haorenfsa after upgrading to the version I am now getting this error when trying to create the cluster:

```
managed/cluster.kafka.aws.crossplane.io  cannot determine creation result - remove the crossplane.io/external-create-pending annotation if it is safe to proceed
```

**Comment by abrarcci** [comment]
Hi @haorenfsa I deleted and re-created the cluster, fyi I do not have the extrernal-name annotation set and now getting this error:
```
Warning  CannotCreateExternalResource  5s (x4 over 6s)  managed/cluster.kafka.aws.crossplane.io  cannot create Cluster in AWS: InvalidParameter: 1 validation error(s) found.
- missing required field, CreateClusterInput.ClusterName.
```
However the [api ref](https://doc.crds.dev/github.com/crossplane/provider-aws/kafka.aws.crossplane.io/Cluster/v1alpha1@v0.35.0) doesn't state there is a name or clusterName field so a bit stuck.

**Comment by haorenfsa** [comment]
> Hi @haorenfsa I deleted and re-created the cluster, fyi I do not have the extrernal-name annotation set and now getting this error:
> 
> ```
> Warning  CannotCreateExternalResource  5s (x4 over 6s)  managed/cluster.kafka.aws.crossplane.io  cannot create Cluster in AWS: InvalidParameter: 1 validation error(s) found.
> - missing required field, CreateClusterInput.ClusterName.
> ```
> 
> However the [api ref](https://doc.crds.dev/github.com/crossplane/provider-aws/kafka.aws.crossplane.io/Cluster/v1alpha1@v0.35.0) doesn't state there is a name or clusterName field so a bit stuck.

Still bug there, we need another patch

**Pull request merged**
