### PR TITLE
fix(s3) compare unmarshaled policy

### LINKED ISSUE #1757: Fix S3 Bucket Policy update loop
### What happened?
When creating a bucket with the policy you get an update loop, because the JSON strings are compared and they don't always look the same. So the bucket is created but not ready.

### PR DESCRIPTION
**Pull request by Tom1893**
### Description of your changes

In the observe policy in the bucket, the comparison of JSON strings was changed to the comparison between actual JSON objects to prevent the update loop. This way it recognizes that the two objects are the same.

We love pull requests that resolve an open Crossplane issue. If yours does, you
can uncomment the below line to indicate which issue your PR fixes, for example
"Fixes #500":

-->
Fixes #1757

I have:

- [ ] Read and followed Crossplane's [contribution process].
- [ X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by MisterMX** [comment]
@Tom1893 thank you so much for your contribution. Please add unit tests to verify that your changes are actually working and sign and squash your commits. Thanks in advance.

**Comment by kelvinwijaya** [comment]
Hi,

**Comment by kelvinwijaya** [comment]
Hi @Tom1893 @MisterMX ,

I have just run test against the master build. 

It seems error still persist and the Bucket Policy api are being triggered multiple times, state of the bucket also stuck in the "Creating" state.

image


This is my sample Bucket manifest created from composition

```
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-create-pending: "2023-06-12T06:51:33Z"
    crossplane.io/external-create-succeeded: "2023-06-12T06:51:35Z"
    crossplane.io/external-name: test-bucket-xxxx
  creationTimestamp: "2023-06-12T06:51:33Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: test-bucket-mfqjc-
  generation: 2
  labels:
    crossplane.io/claim-name: test-bucket
    crossplane.io/claim-namespace: my-namespace
    crossplane.io/composite: test-bucket-mfqjc
  name: test-bucket-mfqjc-hnx2w
  ownerReferences:
  - apiVersion: crd.aws.acme.domain/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: S3Bucket
    name: test-bucket-mfqjc
    uid: b743c14a-2276-4744-b639-e16b9f31c99b
  resourceVersion: "930007057"
  uid: 9cf10dcd-f145-4c5e-8be1-9f95c23bf681
spec:
  deletionPolicy: Delete
  forProvider:
    corsConfiguration:
      corsRules:
      - allowedHeaders:
        - '*'
        allowedMethods:
        - PUT
        - POST
        - DELETE
        allowedOrigins:
        - '*'
      - allowedMethods:
        - GET
        allowedOrigins:
        - '*'
    lifecycleConfiguration:
      rules:
      - expiration:
          expiredObjectDeleteMarker: true
        noncurrentVersionExpiration:
          noncurrentDays: 1
        status: Enabled
    locationConstraint: us-east-1
    objectLockEnabledForBucket: false
    objectOwnership: BucketOwnerEnforced
    paymentConfiguration:
      payer: BucketOwner
    policy:
      statements:
      - action:
        - s3:PutObject
        condition:
        - conditions:
          - key: s3:x-amz-server-side-encryption
            listValue:
            - AES256
            - aws:kms
          operatorKey: StringNotEquals
        effect: Deny
        principal:
          allowAnon: true
        resource:
        - arn:aws:s3:::test-bucket-xxxx/*
        sid: DenyIncorrectEncryptionHeader
      - action:
        - s3:PutObject
        condition:
        - conditions:
          - booleanValue: true
            key: s3:x-amz-server-side-encryption
          operatorKey: Bool
        effect: Deny
        principal:
          allowAnon: true
        resource:
        - arn:aws:s3:::test-bucket-xxxx/*
        sid: DenyUnEncryptedObjectUploads
      - action:
        - s3:GetBucketLocation
        - s3:GetBucketVersioning
        - s3:GetLifecycleConfiguration
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:GetObjectVersion
        - s3:GetObjectTagging
        - s3:GetObjectRetention
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
        - s3:ListBucket
        - s3:ListBucketVersions
        condition:
        - conditions:
          - key: aws:PrincipalAccount
            stringValue: "123456789012"
          operatorKey: StringEquals
        effect: Allow
        principal:
          allowAnon: true
        resource:
        - arn:aws:s3:::test-bucket-xxxx
        - arn:aws:s3:::test-bucket-xxxx/*
        sid: AllowTenantReadWrite
      - action:
        - s3:*
        condition:
        - conditions:
          - booleanValue: false
            key: aws:SecureTransport
          operatorKey: Bool
        effect: Deny
        principal:
          allowAnon: true
        resource:
        - arn:aws:s3:::test-bucket-xxxx
        - arn:aws:s3:::test-bucket-xxxx/*
        sid: AllowSSLRequestsOnly
      version: "2012-10-17"
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
    tagging:
      tagSet:
      - key: version
        value: ""
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: aws-provider
  writeConnectionSecretToRef:
    name: test-bucket-mfqjc
    namespace: crossplane-system
status:
  atProvider:
    arn: arn:aws:s3:::test-csbucket-xxxx
  conditions:
  - lastTransitionTime: "2023-06-12T06:51:35Z"
    reason: Creating
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-06-12T06:51:35Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
```

**Comment by kelvinwijaya** [comment]
Hey @Tom1893 @MisterMX ,

Based on my observations, if i put more than 1 statements in the policy, then the status will stuck in "Creating" state, else it will be just fine

**Pull request merged**
