### PR TITLE
Ignore principals order when comparing policies

### PR DESCRIPTION
**Pull request by max-melentyev**
### Description of your changes

AWS returns principals items in a random order so provider-aws should ignore it to not consider policies changed.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

- Existing and new tests

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by MisterMX — COMMENTED** [review]
LGTM. @max-melentyev can you squash your changes in a single commit and adjust the commit message the follow the [conventional commit guidelines](https://www.conventionalcommits.org/en/v1.0.0/#summary) (`fix: ...`)?

**Comment by MisterMX** [comment]
@max-melentyev can you rebase on the latest master and resolve the conflicts?

**Comment by max-melentyev** [comment]
rebased

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much @max-melentyev!

**Pull request merged**
