### PR TITLE
feat(aws): bump aws-sdk-go to v1.44.174

### PR DESCRIPTION
**Pull request by AlexLast**
### Description of your changes

We need to make use of a new RDS `DBInstance` parameter that is in a later version of the AWS SDK, specifically being able to set `CACertificateIdentifier`. This pull request bumps `aws-sdk-go` to version `v1.44.174`, the version where this parameter was introduced.

I've added all new resources to `ignore.resource_names` so they can be introduced more carefully, however let me know if this isn't the correct approach.

Also needed to slightly refactor how tagging works in `cloudwatchlogs/loggroup/setup.go` to work around some deprecation warnings.

I have:

- [x] Read and followed Crossplane's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
~~Yet to do any testing, however I'll be running a build locally to test out some resources and ensure things are working as expected.~~

- [x] Run a local build and ensured the following resources that we use were working as expected: `S3.Bucket`, `S3.BucketPolicy`, `IAM.Role`, `IAM.Policy`, `IAM.RolePolicyAttachment`, `EC2.SecurityGroup`, `EC2.SecurityGroupRule`, `RDS.DBSubnetGroup`, `RDS.DBCluster`, `RDS.DBClusterParameterGroup`, `RDS.DBInstance`, `Kinesis.Stream`, `DynamoDB.Table`,  `KMS.Key`.
- [x] Ensured refactored tagging for `CloudwatchLogs.LogGroup` is working as expected.

### CODE REVIEW

**Comment by haarchri** [comment]
thanks for driving this - overall looks good 
lets implement first https://github.com/crossplane-contrib/provider-aws/pull/1689 then we have a check for breaking changes in the crds ;)

**Comment by AlexLast** [comment]
@haarchri Sure, let me know when it's merged and I'll rebase

**Comment by haarchri** [comment]
done! @AlexLast  can you rebase ? thanks ;)

**Comment by AlexLast** [comment]
@haarchri Have rebased and re run `make reviewable test` - no changes.

Looks like there are a couple of resources reported by `report-breaking-changes`, although seems to be some new status fields and some parameters that are no longer required.

**Comment by haarchri** [comment]
thats what i wanted to see ;)

**Review by haarchri — APPROVED** [review]
LGTM

**Pull request merged**
